[General]
category=@Invalid()
contentType=@Invalid()
language=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\x14\0\x43\0h\0i\0n\0\x65\0s\0\x65\0|\0z\0h)

[download]
dir=/home/sec/kiwix

[view]
zoomFactor=1
